### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by jose-caballero**
Logrotation option dataext does not exit. Most probably it meant to be dateext.

### CODE REVIEW

**Review by DrDaveD — APPROVED** [review]
Indeed, thanks for catching that.

I guess the current entry is ignored.  Or does it cause an error message somewhere?

Do you need it in a new release, or should I just include it in the next release that is made for another reason?

**Comment by jose-caballero** [comment]
It triggers emails like this one [*], every time the cron runs.
A new RPM asap would be helpful. 

Cheers,
Jose


=====================================================
[*] 

To: root@stratum01.gridpp.rl.ac.uk
Subject: Cron <root@stratum01> run-parts /etc/cron.daily

/etc/cron.daily/logrotate:

error: cvmfs-hastratum1:5 unknown option 'dataext' -- ignoring line

**Comment by DrDaveD** [comment]
It's amazing that nobody has reported this before.  It has been there since May 2016.  I guess the FNAL and IHEP system admins ignore the output from /etc/cron.daily, and I must not receive the output on my test VMs.

**Comment by DrDaveD** [comment]
Ok it should be available in version 2.31 now

**Pull request merged**
